export type RecommendationStatus = 'success' | 'manual_review' | 'no_fit' | 'split_recommendation';

export interface Product { product_id: number; sku_code: string; product_name?: string; category_name?: string; subcategory_name?: string; base_uom?: string; gross_weight_kg?: number; volume_m3?: number; }
export interface TruckType { truck_type_id: number; truck_code?: string; truck_name?: string; max_payload_kg?: number; cargo_volume_m3?: number; truck_group?: string; }
export interface StackingRule { stacking_rule_id: number; rule_code?: string; category_name?: string; subcategory_name?: string; max_stack_layer?: number; is_active?: boolean; }
export interface Customer { customer_id: number; customer_code?: string; customer_name?: string; city?: string; zone?: string; region?: string; }
export interface VendorAllocation { vendor_lane_allocation_id: number; customer_code?: string; ship_to_code?: string; route_code?: string; truck_name?: string; priority_no?: number; is_active?: boolean; }
export interface OrderListItem { order_id: number; order_no?: string; customer_name?: string; planned_delivery_date?: string; status?: string; line_count?: number; total_weight_kg?: number; total_volume_m3?: number; }
export interface OrderDetail { header: OrderListItem & { source_order_type?: string; source_reference_no?: string;}; latest_run_id?: number | null; items: Array<{ order_item_id:number; line_no:number; sku_code?:string; product_name?:string; sap_shipping_qty?:number; base_qty?:number; qty_uom?:string; gross_weight_total_kg?:number; volume_total_m3?:number; stacking_rule_code?:string; max_stack_layer?:number; }>; summary: { total_weight_kg:number; total_volume_m3:number; item_count:number } }
export interface CubicationCandidate { candidate_id:number; truck_name?:string; max_payload_kg?:number; cargo_volume_m3?:number; weight_utilization_pct?:number; volume_utilization_pct?:number; pass_weight?:boolean; pass_volume?:boolean; pass_floor_area?:boolean; pass_height?:boolean; rank_no?:number; rejection_reason?:string; }
export interface SimulationDetail { run_id:number; order_id:number; status?:string; recommendation_status?:RecommendationStatus; recommendation_reason?:string; algorithm_version?:string; created_at?:string; run_items:Array<{ run_item_id:number; sku_code?:string; product_name?:string; qty_shipping_pack?:number; total_weight_kg?:number; total_volume_m3?:number; max_stack_layer?:number; stack_layers_used?:number; }>; candidates: CubicationCandidate[]; split_recommendation?: string[] }
export interface ImportLog { import_log_id:number; source_name?:string; file_name?:string; status?:string; row_count?:number; success_count?:number; error_count?:number; started_at?:string; finished_at?:string; }
export interface ValidationError { validation_error_id:number; row_identifier?:string; field_name?:string; error_code?:string; error_message?:string; severity?:string; }
